// Alert
export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";

// metrics
export const LOADING_METRIC_START = "LOADING_METRIC_START";
export const LOAD_METRIC_SUCCESS = "LOAD_METRIC_SUCCESS";
export const LOAD_METRIC_FAIL = "LOAD_METRIC_FAIL";

export const ADDING_METRIC_START = "ADDING_METRIC_START";
export const ADD_METRIC_SUCCESS = "ADD_METRIC_SUCCESS";
export const ADD_METRIC_FAIL = "ADD_METRIC_FAIL";

export const LOADING_AVERAGE_METRIC_START = "LOADING_AVERAGE_METRIC_START";
export const LOAD_AVERAGE_METRIC_SUCCESS = "LOAD_AVERAGE_METRIC_SUCCESS";
export const LOAD_AVERAGE_METRIC_FAIL = "LOAD_AVERAGE_METRIC_FAIL";
